DjangoCorp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path
from .views import cart_view, cart_add

app_name = 'cart'

urlpatterns = [
    path('', cart_view, name='cart-view'),
    path('delete/', cart_view, name='delete-to-cart'),
    path('delete/', cart_view, name='update-to-cart'),
    path('add/', cart_add, name='add-to-cart'),
]

shop/urls.py
from django.urls import path
from .views import products_view, product_detail_view, category_list

app_name = 'shop'

urlpatterns = [
    path('', products_view, name='products'),
    path('<slug:slug>/', product_detail_view, name='product_detail'),
    path('search/<slug:slug>/', category_list, name='category_list'),
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
import random
from django.db import models
from django.utils.text import slugify
import string
from django.urls import reverse


def rand_slug():
    return ''.join(random.choices(string.ascii_letters + string.digits, k=10))


class Category(models.Model):
    name = models.CharField(verbose_name="Категория", max_length=100, db_index=True)
    parent = models.ForeignKey('self', verbose_name='Родитель', null=True, blank=True,
                                        related_name='children', on_delete=models.CASCADE)
    slug = models.SlugField(verbose_name='URL', max_length=250, unique=True, null=False, editable=True)
    created_at = models.DateTimeField('Дата создания', auto_now_add=True)

    class Meta:
        unique_together = (('parent', 'slug'),)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        full_path = [self.name]
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent
        return ' > '.join(full_path[::-1])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(rand_slug() + '-' + self.name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('shop:category_list', kwargs={'slug': self.slug})


class Product(models.Model):
    title = models.CharField('Название', max_length=250, db_index=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    brand = models.CharField('Бренд', max_length=100, db_index=True)
    description = models.TextField('Описание', blank=True)
    image = models.ImageField(verbose_name='Изображение', upload_to='products', null=True, blank=True)
    slug = models.SlugField(verbose_name='URL', max_length=250, unique=True, null=False, editable=True)
    price = models.DecimalField(verbose_name='Цена', max_digits=10, decimal_places=2, default=99.99)
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'slug': self.slug})


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(available=True)


class ProductProxy(Product):

    objects = ProductManager()

    class Meta:
        proxy = True

cart/views.py
from django.shortcuts import render, get_object_or_404
from .context_processors import cart
from shop.models import ProductProxy
from django.http import JsonResponse
from .cart import Cart


def cart_view(request):
    return render(request, 'cart/cart_view.html')


def cart_add(request):
    cart = Cart(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))

        product = get_object_or_404(ProductProxy, id=product_id)

        cart.add(product=product, quantity=product_qty)

        cart_qty = cart.__len__()

        response = JsonResponse({
            'qty': cart_qty,
            'product': product.title
        })

        return response


def cart_delete(request):
    pass


def cart_update(request):
    pass

shop/views.py
from django.shortcuts import render
from .models import ProductProxy, Category, Product


def products_view(request):
    products = ProductProxy.objects.all()
    context = {
        'products': products
    }
    return render(request, 'shop/products.html', context)


def product_detail_view(request, slug):
    product = ProductProxy.objects.get(slug=slug)
    context = {
        'product': product
    }
    return render(request, 'shop/product_detail.html', context)


def category_list(request, slug):
    category = Category.objects.get(slug=slug)
    products = Product.objects.select_related('category').filter(category=category)
    context = {
        'category': category,
        'products': products
    }
    return render(request, 'shop/category_list.html', context)

cart/templates/cart/cart_view.html
{% include "base.html" %} {% load static %} {% block content %}

<main class="pt-5">
  <div class="container">
    <h1 class="h5">Shopping cart</h1>

    <hr />
{##}
{#    {% for item in cart %}#}
{#    {% with product=item.product %}#}




    <br />

    <div class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">
        <img
          class="img-fluid mx-auto d-block"
          width="200px"
          alt="Responsive image"
          src="{{product.image.url}}"
        />
      </div>

      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a
          href="{{product.get_absolute_url}}"
          class="text-info text-decoration-none"
        >
          <h1 class="h5 pt-2">{{product.title}}</h1>
        </a>

        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Product</div>

              <div class="col-6 text-end">
                <span class="h6 fw-bold">$ {{ product.price }}</span>
              </div>
            </div>
          </div>

          <div class="col">
            <div class="row p-3">
              <div class="col-12">
                <label for="select">Qty</label>

                &nbsp;

                <select id="select{{product.id}}">
                  <option selected>{{item.qty}}</option>

                  <option value="">1</option>

                  <option value="">2</option>

                  <option value="">3</option>

                  <option value="">4</option>
                </select>

                <br />
                <br />

                <button
                  type="button"
                  data-index="{{product.id}}"
                  class="btn btn-primary btn-sm update-button"
                >
                  Update
                </button>

                &nbsp;

                <button
                  type="button"
                  class="btn btn-danger btn-sm delete-button"
                  data-index="{{product.id}}"
                >
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{#    {% endwith %}#}
{#    {% endfor %}#}

    <div class="col-12 text-end">
      <div class="h6 fw-bold">
        Total: $
        <div id="total" class="d-inline-flex">
          {{ cart.get_total_price }}
        </div>
      </div>
    </div>
  </div>

  <br />
  <br />
</main>

<script>
    $(document).on('click', '.delete-button', function(e){
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: '{% url "cart:delete-to-cart" %}',
            data: {
                product_id: $(this).data('index'),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function(response){
                document.getElementById('lblCartCount').textContent = response.qty
                document.getElementById('total').textContent = response.total

                location.reload()
            },
            error: function(error, status){
                console.log(error)
            }
        })
    });

    $(document).on('click', '.update-button', function(e){
        e.preventDefault();

        var product_id = $(this).data('index')

        $.ajax({
            type: 'POST',
            url: '{% url "cart:update-to-cart" %}',
            data: {
                product_id: $(this).data('index'),
                product_qty: $('#select'+product_id+ ' option:selected').text(),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function(response){
                document.getElementById('lblCartCount').textContent = response.qty
                document.getElementById('total').textContent = response.total

                location.reload()
            },
            error: function(error, status){
                console.log(error)
            }
        })
    });
</script>

{% endblock %}

shop/templates/base.html
{% load static %}

<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- CSS -->

    <link
      rel="stylesheet"
      href="https://bootswatch.com/5/flatly/bootstrap.min.css"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <!-- JavaScript -->

    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>

    <!-- JavaScript Bundle with Popper -->

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>

    <title>BigCorp</title>

    <style>
        .badge {
        padding-left: 9px;
        padding-right: 9px;
        -webkit-border-radius: 9px;
        -moz-border-radius: 9px;
        border-radius: 9px;
      }

      .label-warning[href],
      .badge-warning[href] {
        background-color: #c67605;
      }
      #lblCartCount {
          font-size: 12px;
          background: #3c9700;
          color: #fff;
          padding: 0 5px;
          vertical-align: top;
          margin-left: -2px;
      }
      a {
        font-size: 14px;
        font-weight: 700;
      }
      .superNav {
        font-size: 13px;
      }
      .form-control {
        outline: none !important;
        box-shadow: none !important;
      }
      .navbar-nav li:hover > ul.dropdown-menu {
        display: block;
      }
      .dropdown-submenu {
        position: relative;
      }
      .dropdown-submenu > .dropdown-menu {
        top: 0;
        left: 100%;
        margin-top: -6px;
      }

      /* rotate caret on hover */
      .dropdown-menu > li > a:hover:after {
        text-decoration: underline;
        transform: rotate(-90deg);
      }
      @media screen and (max-width: 540px) {
        .centerOnMobile {
          text-align: center;
        }
      }
    </style>
  </head>

  <body>
    <div class="superNav border-bottom py-2 bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 centerOnMobile">
            <select class="me-3 border-0 bg-light">
              <option value="en-us">EN-US</option>
            </select>
            <span
              class="d-none d-lg-inline-block d-md-inline-block d-sm-inline-block d-xs-none me-3"
              ><strong>info@somedomain.com</strong></span
            >
            <span class="me-3"
              ><i class="fa-solid fa-phone me-1 text-warning"></i>
              <strong>1-800-123-1234</strong></span
            >
          </div>
          <div
            class="col-lg-6 col-md-6 col-sm-12 col-xs-12 d-none d-lg-block d-md-block-d-sm-block d-xs-none text-end"
          >
            <span class="me-3"
              ><i class="fa-solid fa-truck text-muted me-1"></i
              ><a class="text-muted" href="#">Shipping</a></span
            >
            <span class="me-3"
              ><i class="fa-solid fa-file text-muted me-2"></i
              ><a class="text-muted" href="#">Policy</a></span
            >
          </div>
        </div>
      </div>
    </div>
    <nav
      class="navbar navbar-expand-lg bg-white sticky-top navbar-light p-3 shadow-sm "
    >
      <div class="container">
        <a class="navbar-brand" href="{% url 'shop:products' %}"
          ><i class="fa-solid fa-shop me-2"></i>
          <strong>BigCorp SHOP</strong></a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="mx-auto my-3 d-lg-none d-sm-block d-xs-block">
          <div class="input-group">
            <span class="border-success input-group-text bg-success text-white"
              ><i class="fa-solid fa-magnifying-glass"></i
            ></span>
            <input
              type="text"
              class="form-control border-success"
              style="color: #7a7a7a"
            />
            <button class="btn btn-success text-white">Search</button>
          </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <div class="ms-auto d-none d-lg-block">
            <div class="input-group">
              <span
                class="border-success input-group-text bg-success text-white"
                ><i class="fa-solid fa-magnifying-glass"></i
              ></span>
              <input
                type="text"
                class="form-control border-success"
                style="color: #7a7a7a"
              />
              <button class="btn btn-success text-white">Search</button>
            </div>
          </div>
          <ul class="navbar-nav ms-auto">
            {% for i in categories %}

            {% if not i.children.all %}
              <li class="nav-item">
                <a class="nav-link" href="{{i.get_absolute_url}}">{{i.name|upper }}</a>
              </li>
            {% else %}
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="{{i.get_absolute_url}}"
                  id="navbarDropdownMenuLink"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                {{i.name|upper}}
              </a>
                <ul
                  class="dropdown-menu"
                  aria-labelledby="navbarDropdownMenuLink"
                >
                  {% for obj in i.children.all %} {% if not obj.children.all %}
                    <li><a class="dropdown-item" href="{{obj.get_absolute_url}}">{{obj.name|upper}}</a></li>
                  {% else %}
                    <li class="dropdown-submenu">
                      <a class="dropdown-item dropdown-toggle" href="{{obj.get_absolute_url}}">{{obj.name|upper}}</a>

                      <ul class="dropdown-menu">
                    {% for subobj in obj.children.all %} {% if not subobj.children.all %}
                        <li>
                          <a class="dropdown-item" href="{{subobj.get_absolute_url}}">{{subobj.name|upper}}</a>
                        </li>
                    {% else %}
                    <li class="dropdown-submenu">
                      <a class="dropdown-item dropdown-toggle" href="{{subobj.get_absolute_url}}">{{subobj.name|upper}}</a>

                      <ul class="dropdown-menu">
                        {% for lastobj in subobj.children.all %}
                        <li>
                          <a class="dropdown-item" href="{{lastobj.get_absolute_url}}">{{lastobj.name|upper}}</a>
                        </li>
                       {% endfor %}
                      </ul>
                    </li>
                    {% endif %} {% endfor %}
                  </ul>
                </li>
                {% endif %} {% endfor %}
              </ul>
            </li>
            {% endif %} {% endfor %}
          </ul>
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link mx-2 text-uppercase" href="{% url 'cart:cart-view' %}"
                > <i class="fa fa-shopping-cart" aria-hidden="true"> </i> Cart
                <span id="lblCartCount" class="badge badge-warning ">

                  {% with cart_qty=cart|length%}
                    {% if cart_qty > 0 %}
                    {{cart_qty}}
                    {% else %}
                      0
                    {% endif %}

                  {% endwith %}
                </span>
                </a>
            </li>
            <li class="nav-item">
              <a class="nav-link mx-2 text-uppercase" href="#"
                ><i class="fa-solid fa-circle-user me-1"></i> Account</a
              >
            </li>

          </ul>
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock %}
  </body>
</html>

shop/templates/shop/category_list.html
{% extends "base.html" %}

{% load static %}


{% block content %}


<main>
  
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5"> {{category.name|capfirst}} </div>


      <hr>

      <br>


      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

      {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">

            <div class="card-body">
              <p class="card-text">
                <a class="text-info text-decoration-none" href="{{product.get_absolute_url}}"> {{product.title|capfirst}} </a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <h5> $ {{product.price}} </h5>
              </div>
            </div>
          </div>
        </div>

       {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

shop/templates/shop/product_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="container">
        <main class="pt-5">
            <div class="row g-3">
                <div class="col-md-5 col-lg-5 order-md-first bg-light">
                    <img class="img-fluid mx-auto d-block" alt="Responsive image" src="{{product.image.url}}"> <!-- Product image -->
                </div>
                <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                    <h1 class="mb-0 h4"> {{product.name}}</h1>
                    <strong>{{product.brand}}</strong>
                    <hr>
                    <br>
                    <p> {{product.description}} </p>
                    <div class="border">
                        <div class="col border-bottom">
                            <div class="row p-3">
                                <div class="col-6"> Price </div>
                                <div class="col-6 text-end"><span class="h4 fw-bold">$ {{product.price}}</span></div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="row p-3">
                                <div class="col-6">
                                    <label for="select">Qty</label>
                                    &nbsp;
                                    <select id="select">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                    </select>
                                </div>
                                <div class="col-6 text-end">
                                    <button type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm">
                                    Add to cart
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <br>
    </div>
    <script>
        $(document).on('click', '#add-button', function(e){
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url 'cart:add-to-cart' %}',
                data: {
                    product_id: $('#add-button').val(),
                    product_qty: $('#select option:selected').text(),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },
                success: function(response) {
                    document.getElementById('lblCartCount').textContent = response.qty
                },
                error: function(error) {
                    console.log(error)
                },
            })
        })
    </script>

{% endblock %}

shop/templates/shop/products.html
{% extends 'base.html' %}

{% block content %}


    <!-- Introduction section -->

<section class="py-4 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h4>Choose and it is in your hands.</h4>

        <br />

        <p class="lead text-muted">Browse and make the best deal</p>

        <br />

        <a href="#" class="btn btn-success my-2"> Create an account </a>
      </div>
    </div>
  </section>

  <!-- All products section -->

  <section class="album py-5 bg-light">
    <div class="container">
      <div class="pb-3 h5">All products</div>

      <hr />

      <br />

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

          {% for product in products %}
        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}" />
            <div class="card-body">
              <p class="card-text ">
                <a class="text-black  text-decoration-none fs-4" href="{{product.get_absolute_url}}">{{product.title|capfirst}}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center badge bg-success text-wrap" style="width: 6rem;">
                <h5>$ {{product.price}}</h5>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock %}